"""VoiceMCP — Google-only path. NO third-party telephony.

How the "agent calls Mom" wow-moment works without a phone company:

1. The agent decides what to say (Gemini Pro generates the Turkish line).
2. We return a `call_intent` payload: the recipient, the language, the script,
   and a one-time `live_session_id`.
3. The demo web UI opens a simulated phone-call modal ("Ahmet's phone, ringing…").
4. The browser opens a Gemini Live audio session with that `live_session_id`
   and the agent's voice streams in real time — Turkish, low-latency, native.
5. A live waveform + word-by-word caption renders as Gemini speaks.

So the "phone call" is *audibly* a real Gemini Live stream, *visually* a phone
UI. Pure Google. No Twilio. No external dependencies. Free under the hackathon
$500 credits.

For pre-recorded fallback (e.g. demo video render where Live latency hurts),
we expose synth_tts() backed by Google Cloud Text-to-Speech.
"""
from __future__ import annotations

import logging
import secrets
from typing import Any

from ..config import settings

logger = logging.getLogger("vitacare.mcp.voice")


async def outbound_call(text: str, lang: str, to: str) -> dict[str, Any]:
    """Return a call-intent payload the demo UI binds to a Gemini Live session.

    No phone call is placed — the demo browser plays the agent's voice via Gemini Live,
    inside a phone-call modal. Pure Google stack.
    """
    session_id = f"live_{secrets.token_hex(8)}"
    logger.info("VoiceMCP[gemini-live] call_intent lang=%s recipient=%s session=%s", lang, to, session_id)
    return {
        "kind": "call_intent",
        "transport": "gemini-live",
        "live_session_id": session_id,
        "live_model": settings.gemini_model_live,
        "lang": lang,
        "recipient_display": to,
        "script": text,
        "stub": False,
    }


async def synth_tts(text: str, lang: str = "tr-TR") -> dict[str, Any]:
    """Cloud Text-to-Speech fallback — returns a payload the UI plays as audio.

    Used when Live latency would hurt (e.g. demo video render). Streams an
    MP3 generated by Google Cloud TTS. Free tier covers all hackathon demo needs.
    """
    # Real impl: from google.cloud import texttospeech; client.synthesize_speech(...)
    # Skeleton: return an unsigned payload the web layer will request via /tts.
    return {"kind": "tts", "text": text, "lang": lang, "voice": "tr-TR-Standard-A"}
